### ISSUE TITLE
'this' keyword is equivalent to 'undefined'

### ISSUE THREAD

**Issue by JohnRSim** [kaisermann/svelte-i18n#33] opened 2020-01-03 09:12 UTC
**Env**
"svelte-i18n": "^2.1.1"
"sapper": "^0.27.0",
"svelte": "^3.0.0"

**Describe the bug**
Adding the following shows trail of debug logs within the console.

```
//i18n.js
import { register, init } from 'svelte-i18n';
```

**Logs**
<details>
  <summary>console log</summary>

> sapper dev

✔ server (1.8s)
• client
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
1: var __extends = (this && this.__extends) || (function () {
                    ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
1: var __extends = (this && this.__extends) || (function () {
                            ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
12:     };
13: })();
14: var __spreadArrays = (this && this.__spreadArrays) || function () {
                          ^
15:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
16:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
12:     };
13: })();
14: var __spreadArrays = (this && this.__spreadArrays) || function () {
                                  ^
15:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
16:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
4: See the accompanying LICENSE file for terms.
5: */
6: var __assign = (this && this.__assign) || function () {
                   ^
7:     __assign = Object.assign || function(t) {
8:         for (var s, i = 1, n = arguments.length; i < n; i++) {
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
4: See the accompanying LICENSE file for terms.
5: */
6: var __assign = (this && this.__assign) || function () {
                           ^
7:     __assign = Object.assign || function(t) {
8:         for (var s, i = 1, n = arguments.length; i < n; i++) {
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
4: See the accompanying LICENSE file for terms.
5: */
6: var __spreadArrays = (this && this.__spreadArrays) || function () {
                         ^
7:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
8:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
4: See the accompanying LICENSE file for terms.
5: */
6: var __spreadArrays = (this && this.__spreadArrays) || function () {
                                 ^
7:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
8:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
 7: // tslint:disable:no-consecutive-blank-lines
 8: // tslint:disable:align
 9: var __extends = (this && this.__extends) || (function () {
                     ^
10:     var extendStatics = function (d, b) {
11:         extendStatics = Object.setPrototypeOf ||
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
 7: // tslint:disable:no-consecutive-blank-lines
 8: // tslint:disable:align
 9: var __extends = (this && this.__extends) || (function () {
                             ^
10:     var extendStatics = function (d, b) {
11:         extendStatics = Object.setPrototypeOf ||
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
20:     };
21: })();
22: var __assign = (this && this.__assign) || function () {
                    ^
23:     __assign = Object.assign || function(t) {
24:         for (var s, i = 1, n = arguments.length; i < n; i++) {
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
20:     };
21: })();
22: var __assign = (this && this.__assign) || function () {
                            ^
23:     __assign = Object.assign || function(t) {
24:         for (var s, i = 1, n = arguments.length; i < n; i++) {
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
1: var __assign = (this && this.__assign) || function () {
                   ^
2:     __assign = Object.assign || function(t) {
3:         for (var s, i = 1, n = arguments.length; i < n; i++) {
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
1: var __assign = (this && this.__assign) || function () {
                           ^
2:     __assign = Object.assign || function(t) {
3:         for (var s, i = 1, n = arguments.length; i < n; i++) {
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
1: var __spreadArrays = (this && this.__spreadArrays) || function () {
                         ^
2:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
3:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
1: var __spreadArrays = (this && this.__spreadArrays) || function () {
                                 ^
2:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
3:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
✔ service worker (27ms)
> Listening on http://localhost:3000

</details>

When accessing localhost in a browser after adding the following to _layout.svelte
```
<script context="module">
  import { waitLocale } from 'svelte-i18n';

  export async function preload() {
    // awaits for the loading of the 'en-US' and 'en' dictionaries
    return waitLocale();
  }
</script>
```

I get the following error within the console and the page no longer loads.

<details>
  <summary>console log</summary>

TypeError: Cannot read property 'split' of null
    at getRelatedLocalesOf (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:4108)
    at hasLocaleQueue (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:2934)
    at flush (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:3039)
    at Object.waitLocale (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:7256)
    at Object.preload (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\user-35f39f10.js:348:20)
    at handle_page (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2410:29)
    at handle_error (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2298:3)
    at handle_page (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2462:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: Cannot read property 'split' of null
    at getRelatedLocalesOf (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:4108)
    at hasLocaleQueue (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:2934)
    at flush (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:3039)
    at Object.waitLocale (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:7256)
    at Object.preload (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\user-35f39f10.js:348:20)
    at handle_page (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2410:29)
    at handle_error (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2298:3)
    at Array.find_route (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2614:3)
    at nth_handler (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2731:14)
    at C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\dev\server\server.js:2731:31

</details>

**Comment by JohnRSim** [comment] 2020-01-03 09:26
[atlasmobileportal-master.zip](https://github.com/kaisermann/svelte-i18n/files/4018628/atlasmobileportal-master.zip)

Attached source

**Comment by kaisermann** [comment] 2020-01-07 23:53
Hey @JohnRSim 👋 

The first issue, about the warnings, is a duplicate of #12. This is rollup being more cautious than it should for this specific case. Please read the aforementioned issue.

About the second one, would you be able to share a repo with the rest of your configs?

**Comment by JohnRSim** [comment] 2020-01-08 10:42
Hi Kaisermann 

I've upgraded from 
```
    "svelte-i18n": "^2.1.1"
```
 to 
```
    "svelte-i18n": "^2.2.0"
```

this morning and it appears to have fixed the issue.

fixed the issue.

**Comment by JohnRSim** [comment] 2020-01-08 10:56
if I run 
```
npm run dev
```
works fine but when I run 
```
npm run export
```
I now get this error: 

```
> Built in 15.7s
> Crawling http://localhost:3000/
TypeError: Cannot read property 'split' of null
    at getRelatedLocalesOf (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:4108)
    at hasLocaleQueue (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:2934)
    at flush (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:3039)
    at Object.waitLocale (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:7275)
    at Object.preload (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\app-46c76819.js:372:20)
    at handle_page (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\server.js:2420:29)
    at handle_error (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\server.js:2308:3)
    at handle_page (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\server.js:2472:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      32 B   (500) index.html
TypeError: Cannot read property 'split' of null
    at getRelatedLocalesOf (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:4108)
    at hasLocaleQueue (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:2934)
    at flush (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:3039)
    at Object.waitLocale (C:\work\fishbowl\gitlab\atlasmobileportal\node_modules\svelte-i18n\dist\i18n.js:15:7275)
    at Object.preload (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\app-46c76819.js:372:20)
    at handle_page (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\server.js:2420:29)
    at handle_error (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\server.js:2308:3)
    at handle_page (C:\work\fishbowl\gitlab\atlasmobileportal\__sapper__\build\server\server.js:2472:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      32 B   (500) service-worker-index.html

> Finished in 16.7s. Type npx serve __sapper__/export to run the app.
```

**Comment by JohnRSim** [comment] 2020-01-08 10:59
[atlasmobileportal-master (1).zip](https://github.com/kaisermann/svelte-i18n/files/4034905/atlasmobileportal-master.1.zip)

Attached my source for review.

**Comment by JohnRSim** [comment] 2020-01-08 11:01
Also looking in _layout I see this message

![image](https://user-images.githubusercontent.com/364208/71973219-46f6e680-3206-11ea-8bf1-30dfcb6bff9e.png)

**Comment by kematzy** [comment] 2020-01-11 03:48
## POSSIBLE SOLUTION:

I too experienced this repeated warning output in the CLI output until a few minutes ago:

```bash
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
4: See the accompanying LICENSE file for terms.
5: */
6: var __assign = (this && this.__assign) || function () {
                   ^
7:     __assign = Object.assign || function(t) {
8:         for (var s, i = 1, n = arguments.length; i < n; i++) {
```

My "fix" is based upon Rich Harris' [answer](https://github.com/rollup/rollup/issues/1518#issuecomment-321875784).

My `rollup.config.js` file now contains the following:

```js
const onwarn = (warning, onwarn) => 
  (warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) || 
  (warning.code === 'THIS_IS_UNDEFINED') || onwarn(warning);
```
The key part added was: 

```js
(warning.code === 'THIS_IS_UNDEFINED')
```

Now all those warnings are gone, but your mileage may vary.

----

### For Reference Only:

I'm using a version of the [mdauner/sapper-tailwindcss-template](https://github.com/mdauner/sapper-tailwindcss-template), with `svelte-i18n` based upon the code from [kaisermann/svelte-i18n example](https://github.com/kaisermann/svelte-i18n/tree/master/example).

Key parts from my 

**`package.json`**

```json
  "dependencies": {
    "@fullhuman/postcss-purgecss": "^1.3.0",
    "autoprefixer": "^9.7.0",
    "compression": "^1.7.1",
    "cssnano": "^4.1.10",
    "polka": "next",
    "postcss": "^7.0.21",
    "postcss-import": "^12.0.1",
    "postcss-url": "^8.0.0",
    "purgecss-from-svelte": "^2.0.2",
    "rollup-plugin-postcss": "^2.0.3",
    "sirv": "^0.4.0",
    "svelte-i18n": "^2.2.1",
    "svelte-preprocess": "^3.1.4",
    "tailwindcss": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.6.3",
    "@babel/runtime": "^7.6.3",
    "@rollup/plugin-json": "^4.0.1",
    "cypress": "^3.8.1",
    "npm-run-all": "^4.1.5",
    "precss": "^4.0.0",
    "rollup": "^1.26.0",
    "rollup-plugin-babel": "^4.0.2",
    "rollup-plugin-commonjs": "^10.0.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-svelte": "^5.0.1",
    "rollup-plugin-terser": "^5.1.2",
    "sapper": "^0.27.0",
    "svelte": "^3.0.0",
    "svelte-image": "^0.1.9"
  }
```

**`rollup.config.js`**

```js
import resolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';
import commonjs from 'rollup-plugin-commonjs';
import svelte from 'rollup-plugin-svelte';
import babel from 'rollup-plugin-babel';
import { terser } from 'rollup-plugin-terser';
import config from 'sapper/config/rollup.js';
import json from '@rollup/plugin-json';
import pkg from './package.json';
import getPreprocessor from "svelte-preprocess";
import postcss from "rollup-plugin-postcss";
import PurgeSvelte from "purgecss-from-svelte";
import path from "path";

const mode = process.env.NODE_ENV;
const dev = mode === 'development';
const legacy = !!process.env.SAPPER_LEGACY_BUILD;

const onwarn = (warning, onwarn) => 
  (warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) || 
  (warning.code === 'THIS_IS_UNDEFINED') || onwarn(warning);
....
```

**Comment by kaisermann** [comment] 2020-01-14 00:32
@JohnRSim Got some time to test your project! You're missing the `init()` call on `server.js` as well as setting the `fallbackLocale`!

1. Add `import './i18n.js'` to your `server.js`
2. Uncomment the `fallbackLocale: 'en'`

And it should be working again 😁 

About the warning, you can do what @kematzy said 👍

**Closed** 2020-01-14 00:32 UTC
Labels: invalid

**Comment by kaisermann** [comment] 2020-01-14 00:35
Added a quick note to the wiki about having to add to the `server.js`!

**Comment by JohnRSim** [comment] 2020-01-14 11:00
Thanks @kaisermann all working now! :)
